name: Update Stats Cache

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Replace random param in README
        run: |
          RANDOM_NUM=$((RANDOM % 900000 + 100000))
          sed -i "s/random=[0-9]*/random=$RANDOM_NUM/g" README.md

      - name: Commit and push if changed
        run: |
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update GitHub Stats cache param"
            git push
          else
            echo "No changes to commit"
          fi
